openapi: 3.0.0
info:
  title: Banking API
  version: 1.0.0
  description: API for a banking application including authentication and transaction operations

servers:
  - url: http://localhost:80

paths:
  /account/auth/signup:
    post:
      tags:
       - account
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
            examples:
                example1:
                  $ref: '#/components/examples/SignupRequestExample'
      responses:
        '200':
          description: Successful signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /account/auth/signin:
    post:
      tags:
       - account
      summary: Sign in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
            examples:
                example1:
                  $ref: '#/components/examples/SigninRequestExample'
      responses:
        '200':
          description: Successful signin
          headers:
            Front-Token:
              schema:
                type: string
            St-Access-Token:
              schema:
                type: string
            St-Refresh-Token:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /transaction/withdraw:
    post:
      tags:
       - transaction
      summary: Withdraw money from an account
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
            examples:
                example1:
                  $ref: '#/components/examples/WithdrawRequestExample'
      responses:
        '200':
          description: Successful withdrawal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
              examples:
                example1:
                  $ref: '#/components/examples/GeneralSuccessResponse'
  /transaction/send:
    post:
      tags:
       - transaction
      summary: Send money to another account
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
            examples:
                example1:
                  $ref: '#/components/examples/SendRequestExample'
      responses:
        '200':
          description: Successful transfer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
              examples:
                example1:
                  $ref: '#/components/examples/GeneralSuccessResponse'
  /account/history:
    get:
      tags:
       - account
      summary: Get transaction history for an account
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          example: 10
        - in: query
          name: page
          schema:
            type: integer
          required: false
          example: 1
        - in: query
          name: accId
          schema:
            type: string
            format: uuid
          required: true
          example: 99505cf6-85ec-4ea4-af55-cc2cb334f4e7
      responses:
        '200':
          description: Successful retrieval of history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryResponse'

  /account/additional-account:
    post:
      tags:
        - account
      summary: Create an additional account
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdditionalAccountRequest'
            examples:
                example1:
                  $ref: '#/components/examples/AdditionalAccountRequestExample'
      responses:
        '200':
          description: Successful account creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalAccountResponse'
              examples:
                example1:
                  $ref: '#/components/examples/GeneralSuccessResponse'
components:
  examples:
    GeneralSuccessResponse:
      value: 
        data: null
        message: "OK"
    SendRequestExample:
      value: 
        accId: 99505cf6-85ec-4ea4-af55-cc2cb334f4e7
        desc: ini desc
        amount: 10000
        toAccId: 99505cf6-85ec-4ea4-af55-cc2cb334f4e7
    WithdrawRequestExample:
      value: 
        accId: 99505cf6-85ec-4ea4-af55-cc2cb334f4e7
        desc: ini desc
        amount: 10000
    SigninRequestExample:
      value:
        formFields:
          - id: email
            value: email2@email.com
          - id: password
            value: password1@
    AdditionalAccountRequestExample:
      value: 
        accType: DEBIT
        accDesc: akun ku
        currency: IDR
    SignupRequestExample:
      value:
        formFields:
          - id: email
            value: email2@email.com
          - id: password
            value: password1@
          - id: name
            value: name
          - id: dateOfBirth
            value: 2006-01-02
          - id: job
            value: job
          - id: address
            value: address
          - id: district
            value: district
          - id: city
            value: city
          - id: province
            value: province
          - id: country
            value: country
          - id: accCurrency
            value: IDR
          - id: accDesc
            value: akun ku
          - id: zip
            value: "123"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    FormField:
      type: object
      properties:
        id:
          type: string
        value:
          type: string

    SignupRequest:
      type: object
      properties:
        formFields:
          type: array
          items:
            $ref: '#/components/schemas/FormField'

    SigninRequest:
      type: object
      properties:
        formFields:
          type: array
          items:
            $ref: '#/components/schemas/FormField'

    AuthResponse:
      type: object
      properties:
        status:
          type: string
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            timeJoined:
              type: integer
              format: int64
            tenantIds:
              type: array
              items:
                type: string

    WithdrawRequest:
      type: object
      properties:
        accId:
          type: string
          format: uuid
        desc:
          type: string
        amount:
          type: number
          format: float

    SendRequest:
      type: object
      properties:
        accId:
          type: string
          format: uuid
        desc:
          type: string
        amount:
          type: number
          format: float
        toAccId:
          type: string
          format: uuid

    TransactionResponse:
      type: object
      properties:
        message:
          type: string

    HistoryResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: 73a97982-ddc7-484e-adca-03e3a8c62556
              reffNum:
                type: string
                format: uuid
                example: 99505cf6-85ec-4ea4-af55-cc2cb334f4e7
              createdAt:
                type: string
                format: date-time
                example: 2024-08-14 20:20:49.53606 +0000 +0000
              accId:
                type: string
                format: uuid
                example: 12de0245-a77a-4001-a985-d2caebdf1493
              trxType:
                type: string
                enum: [POSITIVE, NEGATIVE]
                example: NEGATIVE
              amount:
                type: number
                example: 10000
              status:
                type: string
                example: SUCCESS
              desc:
                type: string
                example: ini desc
              accId2:
                type: string
                format: uuid
                example: 73a97982-ddc7-484e-adca-03e3a8c62556

    AdditionalAccountRequest:
      type: object
      properties:
        accType:
          type: string
          enum: [DEBIT]
        accDesc:
          type: string
        currency:
          type: string

    AdditionalAccountResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        message:
          type: string